/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AdsNecessityDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AdsNecessitiesDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-20T12:56:14.526351600+03:00[Europe/Helsinki]")
public class AdsNecessitiesDTO {
  @SerializedName("necessary")
  private Boolean necessary = null;

  @SerializedName("necessities")
  private List<AdsNecessityDTO> necessities = null;

  public AdsNecessitiesDTO necessary(Boolean necessary) {
    this.necessary = necessary;
    return this;
  }

   /**
   * Get necessary
   * @return necessary
  **/
  @Schema(description = "")
  public Boolean isNecessary() {
    return necessary;
  }

  public void setNecessary(Boolean necessary) {
    this.necessary = necessary;
  }

  public AdsNecessitiesDTO necessities(List<AdsNecessityDTO> necessities) {
    this.necessities = necessities;
    return this;
  }

  public AdsNecessitiesDTO addNecessitiesItem(AdsNecessityDTO necessitiesItem) {
    if (this.necessities == null) {
      this.necessities = new ArrayList<AdsNecessityDTO>();
    }
    this.necessities.add(necessitiesItem);
    return this;
  }

   /**
   * Get necessities
   * @return necessities
  **/
  @Schema(description = "")
  public List<AdsNecessityDTO> getNecessities() {
    return necessities;
  }

  public void setNecessities(List<AdsNecessityDTO> necessities) {
    this.necessities = necessities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdsNecessitiesDTO adsNecessitiesDTO = (AdsNecessitiesDTO) o;
    return Objects.equals(this.necessary, adsNecessitiesDTO.necessary) &&
        Objects.equals(this.necessities, adsNecessitiesDTO.necessities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(necessary, necessities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdsNecessitiesDTO {\n");
    
    sb.append("    necessary: ").append(toIndentedString(necessary)).append("\n");
    sb.append("    necessities: ").append(toIndentedString(necessities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
