/*
 * Ehr ads api
 * Ehitisregistri ads teenus. Kood asub: https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-ads-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AdsProceedingObjectProblemDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AdsProceedingObjectDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-17T14:08:15.631610300+02:00[Europe/Helsinki]")
public class AdsProceedingObjectDTO {
  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("adsOid")
  private String adsOid = null;

  @SerializedName("adobId")
  private String adobId = null;

  /**
   * Gets or Sets objectType
   */
  @JsonAdapter(ObjectTypeEnum.Adapter.class)
  public enum ObjectTypeEnum {
    EE_VALUE_EE_("AdsTypeEnum.EE(value=EE)"),
    K_VALUE_K_("AdsTypeEnum.K(value=K)"),
    ME_VALUE_ME_("AdsTypeEnum.ME(value=ME)"),
    M_VALUE_M_("AdsTypeEnum.M(value=M)");

    private String value;

    ObjectTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ObjectTypeEnum fromValue(String text) {
      for (ObjectTypeEnum b : ObjectTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ObjectTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjectTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ObjectTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ObjectTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("objectType")
  private ObjectTypeEnum objectType = null;

  /**
   * Gets or Sets state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    T("T"),
    K("K"),
    O("O");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("problems")
  private List<AdsProceedingObjectProblemDTO> problems = null;

  public AdsProceedingObjectDTO identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Objekti origtunnus
   * @return identifier
  **/
  @Schema(example = "123231415", description = "Objekti origtunnus")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public AdsProceedingObjectDTO adsOid(String adsOid) {
    this.adsOid = adsOid;
    return this;
  }

   /**
   * Get adsOid
   * @return adsOid
  **/
  @Schema(description = "")
  public String getAdsOid() {
    return adsOid;
  }

  public void setAdsOid(String adsOid) {
    this.adsOid = adsOid;
  }

  public AdsProceedingObjectDTO adobId(String adobId) {
    this.adobId = adobId;
    return this;
  }

   /**
   * Get adobId
   * @return adobId
  **/
  @Schema(description = "")
  public String getAdobId() {
    return adobId;
  }

  public void setAdobId(String adobId) {
    this.adobId = adobId;
  }

  public AdsProceedingObjectDTO objectType(ObjectTypeEnum objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Get objectType
   * @return objectType
  **/
  @Schema(description = "")
  public ObjectTypeEnum getObjectType() {
    return objectType;
  }

  public void setObjectType(ObjectTypeEnum objectType) {
    this.objectType = objectType;
  }

  public AdsProceedingObjectDTO state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @Schema(description = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public AdsProceedingObjectDTO problems(List<AdsProceedingObjectProblemDTO> problems) {
    this.problems = problems;
    return this;
  }

  public AdsProceedingObjectDTO addProblemsItem(AdsProceedingObjectProblemDTO problemsItem) {
    if (this.problems == null) {
      this.problems = new ArrayList<AdsProceedingObjectProblemDTO>();
    }
    this.problems.add(problemsItem);
    return this;
  }

   /**
   * Get problems
   * @return problems
  **/
  @Schema(description = "")
  public List<AdsProceedingObjectProblemDTO> getProblems() {
    return problems;
  }

  public void setProblems(List<AdsProceedingObjectProblemDTO> problems) {
    this.problems = problems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdsProceedingObjectDTO adsProceedingObjectDTO = (AdsProceedingObjectDTO) o;
    return Objects.equals(this.identifier, adsProceedingObjectDTO.identifier) &&
        Objects.equals(this.adsOid, adsProceedingObjectDTO.adsOid) &&
        Objects.equals(this.adobId, adsProceedingObjectDTO.adobId) &&
        Objects.equals(this.objectType, adsProceedingObjectDTO.objectType) &&
        Objects.equals(this.state, adsProceedingObjectDTO.state) &&
        Objects.equals(this.problems, adsProceedingObjectDTO.problems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, adsOid, adobId, objectType, state, problems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdsProceedingObjectDTO {\n");
    
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    adsOid: ").append(toIndentedString(adsOid)).append("\n");
    sb.append("    adobId: ").append(toIndentedString(adobId)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    problems: ").append(toIndentedString(problems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
