/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AdsProceedingDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AdsProceedingsDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-01T15:16:31.615068100+03:00[Europe/Helsinki]")
public class AdsProceedingsDTO {
  @SerializedName("proceedings")
  private List<AdsProceedingDTO> proceedings = null;

  public AdsProceedingsDTO proceedings(List<AdsProceedingDTO> proceedings) {
    this.proceedings = proceedings;
    return this;
  }

  public AdsProceedingsDTO addProceedingsItem(AdsProceedingDTO proceedingsItem) {
    if (this.proceedings == null) {
      this.proceedings = new ArrayList<AdsProceedingDTO>();
    }
    this.proceedings.add(proceedingsItem);
    return this;
  }

   /**
   * Get proceedings
   * @return proceedings
  **/
  @Schema(description = "")
  public List<AdsProceedingDTO> getProceedings() {
    return proceedings;
  }

  public void setProceedings(List<AdsProceedingDTO> proceedings) {
    this.proceedings = proceedings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdsProceedingsDTO adsProceedingsDTO = (AdsProceedingsDTO) o;
    return Objects.equals(this.proceedings, adsProceedingsDTO.proceedings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proceedings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdsProceedingsDTO {\n");
    
    sb.append("    proceedings: ").append(toIndentedString(proceedings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
