/*
 * Ehr ads api
 * Ehitisregistri ads teenus. Kood asub: https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-ads-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AdsXmlDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AdsRequestsXmlDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-17T14:08:15.631610300+02:00[Europe/Helsinki]")
public class AdsRequestsXmlDTO {
  @SerializedName("operationId")
  private Long operationId = null;

  @SerializedName("xmls")
  private List<AdsXmlDTO> xmls = null;

  public AdsRequestsXmlDTO operationId(Long operationId) {
    this.operationId = operationId;
    return this;
  }

   /**
   * Get operationId
   * @return operationId
  **/
  @Schema(description = "")
  public Long getOperationId() {
    return operationId;
  }

  public void setOperationId(Long operationId) {
    this.operationId = operationId;
  }

  public AdsRequestsXmlDTO xmls(List<AdsXmlDTO> xmls) {
    this.xmls = xmls;
    return this;
  }

  public AdsRequestsXmlDTO addXmlsItem(AdsXmlDTO xmlsItem) {
    if (this.xmls == null) {
      this.xmls = new ArrayList<AdsXmlDTO>();
    }
    this.xmls.add(xmlsItem);
    return this;
  }

   /**
   * Get xmls
   * @return xmls
  **/
  @Schema(description = "")
  public List<AdsXmlDTO> getXmls() {
    return xmls;
  }

  public void setXmls(List<AdsXmlDTO> xmls) {
    this.xmls = xmls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdsRequestsXmlDTO adsRequestsXmlDTO = (AdsRequestsXmlDTO) o;
    return Objects.equals(this.operationId, adsRequestsXmlDTO.operationId) &&
        Objects.equals(this.xmls, adsRequestsXmlDTO.xmls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationId, xmls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdsRequestsXmlDTO {\n");
    
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    xmls: ").append(toIndentedString(xmls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
