/*
 * Ehr ads api
 * Ehitisregistri ads teenus. Kood asub: https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-ads-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BuildingDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BuildingsDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-17T14:08:15.631610300+02:00[Europe/Helsinki]")
public class BuildingsDTO {
  @SerializedName("conductorName")
  private String conductorName = null;

  @SerializedName("conductorCode")
  private String conductorCode = null;

  @SerializedName("buildings")
  private List<BuildingDTO> buildings = new ArrayList<BuildingDTO>();

  public BuildingsDTO conductorName(String conductorName) {
    this.conductorName = conductorName;
    return this;
  }

   /**
   * Get conductorName
   * @return conductorName
  **/
  @Schema(required = true, description = "")
  public String getConductorName() {
    return conductorName;
  }

  public void setConductorName(String conductorName) {
    this.conductorName = conductorName;
  }

  public BuildingsDTO conductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
    return this;
  }

   /**
   * Get conductorCode
   * @return conductorCode
  **/
  @Schema(required = true, description = "")
  public String getConductorCode() {
    return conductorCode;
  }

  public void setConductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
  }

  public BuildingsDTO buildings(List<BuildingDTO> buildings) {
    this.buildings = buildings;
    return this;
  }

  public BuildingsDTO addBuildingsItem(BuildingDTO buildingsItem) {
    this.buildings.add(buildingsItem);
    return this;
  }

   /**
   * Get buildings
   * @return buildings
  **/
  @Schema(required = true, description = "")
  public List<BuildingDTO> getBuildings() {
    return buildings;
  }

  public void setBuildings(List<BuildingDTO> buildings) {
    this.buildings = buildings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildingsDTO buildingsDTO = (BuildingsDTO) o;
    return Objects.equals(this.conductorName, buildingsDTO.conductorName) &&
        Objects.equals(this.conductorCode, buildingsDTO.conductorCode) &&
        Objects.equals(this.buildings, buildingsDTO.buildings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conductorName, conductorCode, buildings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildingsDTO {\n");
    
    sb.append("    conductorName: ").append(toIndentedString(conductorName)).append("\n");
    sb.append("    conductorCode: ").append(toIndentedString(conductorCode)).append("\n");
    sb.append("    buildings: ").append(toIndentedString(buildings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
