/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProceedingDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CheckOperationDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-02T14:22:54.670916200+03:00[Europe/Helsinki]")
public class CheckOperationDTO {
  @SerializedName("conductorName")
  private String conductorName = null;

  @SerializedName("conductorCode")
  private String conductorCode = null;

  @SerializedName("proceedings")
  private List<ProceedingDTO> proceedings = null;

  public CheckOperationDTO conductorName(String conductorName) {
    this.conductorName = conductorName;
    return this;
  }

   /**
   * Unique identifier of the Contact.
   * @return conductorName
  **/
  @Schema(example = "1", description = "Unique identifier of the Contact.")
  public String getConductorName() {
    return conductorName;
  }

  public void setConductorName(String conductorName) {
    this.conductorName = conductorName;
  }

  public CheckOperationDTO conductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
    return this;
  }

   /**
   * Unique identifier of the Contact.
   * @return conductorCode
  **/
  @Schema(example = "1", description = "Unique identifier of the Contact.")
  public String getConductorCode() {
    return conductorCode;
  }

  public void setConductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
  }

  public CheckOperationDTO proceedings(List<ProceedingDTO> proceedings) {
    this.proceedings = proceedings;
    return this;
  }

  public CheckOperationDTO addProceedingsItem(ProceedingDTO proceedingsItem) {
    if (this.proceedings == null) {
      this.proceedings = new ArrayList<ProceedingDTO>();
    }
    this.proceedings.add(proceedingsItem);
    return this;
  }

   /**
   * Get proceedings
   * @return proceedings
  **/
  @Schema(description = "")
  public List<ProceedingDTO> getProceedings() {
    return proceedings;
  }

  public void setProceedings(List<ProceedingDTO> proceedings) {
    this.proceedings = proceedings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckOperationDTO checkOperationDTO = (CheckOperationDTO) o;
    return Objects.equals(this.conductorName, checkOperationDTO.conductorName) &&
        Objects.equals(this.conductorCode, checkOperationDTO.conductorCode) &&
        Objects.equals(this.proceedings, checkOperationDTO.proceedings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conductorName, conductorCode, proceedings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckOperationDTO {\n");
    
    sb.append("    conductorName: ").append(toIndentedString(conductorName)).append("\n");
    sb.append("    conductorCode: ").append(toIndentedString(conductorCode)).append("\n");
    sb.append("    proceedings: ").append(toIndentedString(proceedings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
