/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BuildingDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * OperationDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-01T16:33:15.699958100+03:00[Europe/Helsinki]")
public class OperationDTO {
  @SerializedName("conductorName")
  private String conductorName = null;

  @SerializedName("conductorCode")
  private String conductorCode = null;

  @SerializedName("buildings")
  private List<BuildingDTO> buildings = null;

  public OperationDTO conductorName(String conductorName) {
    this.conductorName = conductorName;
    return this;
  }

   /**
   * Unique identifier of the Contact.
   * @return conductorName
  **/
  @Schema(example = "1", description = "Unique identifier of the Contact.")
  public String getConductorName() {
    return conductorName;
  }

  public void setConductorName(String conductorName) {
    this.conductorName = conductorName;
  }

  public OperationDTO conductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
    return this;
  }

   /**
   * Unique identifier of the Contact.
   * @return conductorCode
  **/
  @Schema(example = "1", description = "Unique identifier of the Contact.")
  public String getConductorCode() {
    return conductorCode;
  }

  public void setConductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
  }

  public OperationDTO buildings(List<BuildingDTO> buildings) {
    this.buildings = buildings;
    return this;
  }

  public OperationDTO addBuildingsItem(BuildingDTO buildingsItem) {
    if (this.buildings == null) {
      this.buildings = new ArrayList<BuildingDTO>();
    }
    this.buildings.add(buildingsItem);
    return this;
  }

   /**
   * Get buildings
   * @return buildings
  **/
  @Schema(description = "")
  public List<BuildingDTO> getBuildings() {
    return buildings;
  }

  public void setBuildings(List<BuildingDTO> buildings) {
    this.buildings = buildings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationDTO operationDTO = (OperationDTO) o;
    return Objects.equals(this.conductorName, operationDTO.conductorName) &&
        Objects.equals(this.conductorCode, operationDTO.conductorCode) &&
        Objects.equals(this.buildings, operationDTO.buildings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conductorName, conductorCode, buildings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationDTO {\n");
    
    sb.append("    conductorName: ").append(toIndentedString(conductorName)).append("\n");
    sb.append("    conductorCode: ").append(toIndentedString(conductorCode)).append("\n");
    sb.append("    buildings: ").append(toIndentedString(buildings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
