/*
 * Ehr ads api
 * Ehitisregistri ads teenus. Kood asub: https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-ads-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProceedingDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ProceedingsDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-17T14:08:15.631610300+02:00[Europe/Helsinki]")
public class ProceedingsDTO {
  @SerializedName("conductorName")
  private String conductorName = null;

  @SerializedName("conductorCode")
  private String conductorCode = null;

  @SerializedName("proceedings")
  private List<ProceedingDTO> proceedings = new ArrayList<ProceedingDTO>();

  public ProceedingsDTO conductorName(String conductorName) {
    this.conductorName = conductorName;
    return this;
  }

   /**
   * Ametniku nimi, koos user id&#x27;ga
   * @return conductorName
  **/
  @Schema(example = "Test Test (12345)", required = true, description = "Ametniku nimi, koos user id'ga")
  public String getConductorName() {
    return conductorName;
  }

  public void setConductorName(String conductorName) {
    this.conductorName = conductorName;
  }

  public ProceedingsDTO conductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
    return this;
  }

   /**
   * Ametniku regkood
   * @return conductorCode
  **/
  @Schema(example = "132323", required = true, description = "Ametniku regkood")
  public String getConductorCode() {
    return conductorCode;
  }

  public void setConductorCode(String conductorCode) {
    this.conductorCode = conductorCode;
  }

  public ProceedingsDTO proceedings(List<ProceedingDTO> proceedings) {
    this.proceedings = proceedings;
    return this;
  }

  public ProceedingsDTO addProceedingsItem(ProceedingDTO proceedingsItem) {
    this.proceedings.add(proceedingsItem);
    return this;
  }

   /**
   * Get proceedings
   * @return proceedings
  **/
  @Schema(required = true, description = "")
  public List<ProceedingDTO> getProceedings() {
    return proceedings;
  }

  public void setProceedings(List<ProceedingDTO> proceedings) {
    this.proceedings = proceedings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProceedingsDTO proceedingsDTO = (ProceedingsDTO) o;
    return Objects.equals(this.conductorName, proceedingsDTO.conductorName) &&
        Objects.equals(this.conductorCode, proceedingsDTO.conductorCode) &&
        Objects.equals(this.proceedings, proceedingsDTO.proceedings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conductorName, conductorCode, proceedings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProceedingsDTO {\n");
    
    sb.append("    conductorName: ").append(toIndentedString(conductorName)).append("\n");
    sb.append("    conductorCode: ").append(toIndentedString(conductorCode)).append("\n");
    sb.append("    proceedings: ").append(toIndentedString(proceedings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
