/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ProceedingDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-20T12:56:14.526351600+03:00[Europe/Helsinki]")
public class ProceedingDTO {
  @SerializedName("adsProceedingNumber")
  private Integer adsProceedingNumber = null;

  @SerializedName("buildingId")
  private Long buildingId = null;

  public ProceedingDTO adsProceedingNumber(Integer adsProceedingNumber) {
    this.adsProceedingNumber = adsProceedingNumber;
    return this;
  }

   /**
   * Get adsProceedingNumber
   * @return adsProceedingNumber
  **/
  @Schema(required = true, description = "")
  public Integer getAdsProceedingNumber() {
    return adsProceedingNumber;
  }

  public void setAdsProceedingNumber(Integer adsProceedingNumber) {
    this.adsProceedingNumber = adsProceedingNumber;
  }

  public ProceedingDTO buildingId(Long buildingId) {
    this.buildingId = buildingId;
    return this;
  }

   /**
   * Get buildingId
   * @return buildingId
  **/
  @Schema(required = true, description = "")
  public Long getBuildingId() {
    return buildingId;
  }

  public void setBuildingId(Long buildingId) {
    this.buildingId = buildingId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProceedingDTO proceedingDTO = (ProceedingDTO) o;
    return Objects.equals(this.adsProceedingNumber, proceedingDTO.adsProceedingNumber) &&
        Objects.equals(this.buildingId, proceedingDTO.buildingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adsProceedingNumber, buildingId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProceedingDTO {\n");
    
    sb.append("    adsProceedingNumber: ").append(toIndentedString(adsProceedingNumber)).append("\n");
    sb.append("    buildingId: ").append(toIndentedString(buildingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
