/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AdsProceedingsDTO;
import io.swagger.client.model.AdsXmlRequestDTO;
import io.swagger.client.model.BuildingDTO;
import io.swagger.client.model.CheckOperationDTO;
import io.swagger.client.model.NecessityDTO;
import io.swagger.client.model.OperationDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdsMenetlusApi
 */
@Ignore
public class AdsMenetlusApiTest {

    private final AdsMenetlusApi api = new AdsMenetlusApi();

    /**
     * ADS kontroll esitamine (DELETE, SEND, DELETE, RESTORE)
     *
     * Esitab andmed ADS&#x27;i vastavalt tegevuse järgi. ADS ADSmenadresit päringus on kontrolli tõene.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkTest() throws ApiException {
        OperationDTO body = null;
        String adsType = null;
        AdsProceedingsDTO response = api.check(body, adsType);

        // TODO: test validations
    }
    /**
     * ADS menetluse kontrollimine
     *
     * Esitab ADS&#x27;i ADS menetluse numbri. Positiivse vastuse korral andmed salvestatakse baasi.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkProceedingTest() throws ApiException {
        CheckOperationDTO body = null;
        AdsProceedingsDTO response = api.checkProceeding(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isNeededTest() throws ApiException {
        List<BuildingDTO> body = null;
        String adsType = null;
        List<NecessityDTO> response = api.isNeeded(body, adsType);

        // TODO: test validations
    }
    /**
     * ADS esitamine (DELETE, SEND, DELETE, RESTORE)
     *
     * Esitab andmed ADS&#x27;i vastavalt tegevuse järgi. Positiivse vastuse korral uuendakse ehitise andmeid. ADS ADSmenadresit päringus on kontrolli väär.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendTest() throws ApiException {
        OperationDTO body = null;
        String adsType = null;
        AdsProceedingsDTO response = api.send(body, adsType);

        // TODO: test validations
    }
    /**
     * ADS päringu XML (DELETE, SEND, DELETE, RESTORE)
     *
     * Paneb kokku ADS päringu vastavalt tegevuse järgi ja tagastab kodeeringus xml stringi.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void xmlTest() throws ApiException {
        List<BuildingDTO> body = null;
        String adsType = null;
        List<AdsXmlRequestDTO> response = api.xml(body, adsType);

        // TODO: test validations
    }
}
