/*
 * Ehr ads api
 * Ehitisregistri ads teenus. Kood asub: https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-ads-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AdsNecessitiesDTO;
import io.swagger.client.model.AdsProceedingsDTO;
import io.swagger.client.model.AdsRequestsXmlDTO;
import io.swagger.client.model.BuildingDTO;
import io.swagger.client.model.BuildingsDTO;
import io.swagger.client.model.ProceedingsDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdsProceedingApiControllerApi
 */
@Ignore
public class AdsProceedingApiControllerApiTest {

    private final AdsProceedingApiControllerApi api = new AdsProceedingApiControllerApi();

    /**
     * Tagastab ehitise ads päringu xml
     *
     * Korjab ehitise ads päringu xml kokku /do/{adsType} loogika järgi. Päringut ei tehta.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adsProceedingXmlTest() throws ApiException {
        List<BuildingDTO> body = null;
        String adsType = null;
        AdsRequestsXmlDTO response = api.adsProceedingXml(body, adsType);

        // TODO: test validations
    }
    /**
     * Kontrollib adsis olevat menetlust. Õnnestumise korral salvestakse andmed.
     *
     * Teeb ads menetlusnumbri korral adsi päringu. Päringu kehas peab olema selle menetlusnumbri ehitis. Puudumise korral andmeid ei salvestada.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkAdsProceedingTest() throws ApiException {
        ProceedingsDTO body = null;
        AdsProceedingsDTO response = api.checkAdsProceeding(body);

        // TODO: test validations
    }
    /**
     * Teeb adsi kontrollpäringu (SEND, DELETE, RESTORE). Andmeid ei salvestada.
     *
     * Teeb ads kontrollpäringu ehitise andmete põhjal. Tuleb eristada SEND, DELETE ja RESTORE ads seisundit. SEND korral kogutakse kokku ehitise osad ja ruumikujud, mille adsi esitamise seisund on ADS_ESITAMATA.SEND korral sõltub osa ja ruumikuju ads seisund reeglitest.DELETE korral kogutakse kokku ehitise osad ja ruumikuju ning ads seisund pannakse neile T. Vaadatakse esitamise seisundit ADS_ESITAMATA.RESTORE korral asendakse osa või kuju andmed ära aktuaalsetega, kui aktuaalne eksisteerib ning ads seisund pannakse reeglite järgi. Muidu saab ads seisundi T.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkAdsRequestTest() throws ApiException {
        BuildingsDTO body = null;
        String adsType = null;
        AdsProceedingsDTO response = api.checkAdsRequest(body, adsType);

        // TODO: test validations
    }
    /**
     * Kontrollib ads vajadust (vaatab ads_esitamise seisundit)
     *
     * Kontrollib ehitise ads esitamise seisundit ja tagastab, et kas on vaja esitada.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isAdsNecessaryTest() throws ApiException {
        List<BuildingDTO> body = null;
        String adsType = null;
        AdsNecessitiesDTO response = api.isAdsNecessary(body, adsType);

        // TODO: test validations
    }
    /**
     * Teeb adsi päringu (SEND, DELETE, RESTORE). Andmeid salvestakse õnnestumise korral.
     *
     * Esitab ehitise andmed adsi. Tuleb eristada SEND, DELETE ja RESTORE ads seisundit. SEND korral kogutakse kokku ehitise osad ja ruumikujud, mille adsi esitamise seisund on ADS_ESITAMATA.SEND korral sõltub osa ja ruumikuju ads seisund reeglitest.DELETE korral kogutakse kokku ehitise osad ja ruumikuju ning ads seisund pannakse neile T. Vaadatakse esitamise seisundit ADS_ESITAMATA.RESTORE korral asendakse osa või kuju andmed ära aktuaalsetega, kui aktuaalne eksisteerib ning ads seisund pannakse reeglite järgi. Muidu saab ads seisundi T.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendAdsRequestTest() throws ApiException {
        BuildingsDTO body = null;
        String adsType = null;
        AdsProceedingsDTO response = api.sendAdsRequest(body, adsType);

        // TODO: test validations
    }
}
