/*
 * sample application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AdsNecessitiesDTO;
import io.swagger.client.model.AdsProceedingsDTO;
import io.swagger.client.model.AdsRequestsXmlDTO;
import io.swagger.client.model.BuildingDTO;
import io.swagger.client.model.BuildingsDTO;
import io.swagger.client.model.ProceedingsDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdsProceedingControllerApi
 */
@Ignore
public class AdsProceedingControllerApiTest {

    private final AdsProceedingControllerApi api = new AdsProceedingControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkTest() throws ApiException {
        BuildingsDTO body = null;
        String adsType = null;
        AdsProceedingsDTO response = api.check(body, adsType);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkAdsProceedingTest() throws ApiException {
        ProceedingsDTO body = null;
        AdsProceedingsDTO response = api.checkAdsProceeding(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isNecessaryTest() throws ApiException {
        List<BuildingDTO> body = null;
        String adsType = null;
        AdsNecessitiesDTO response = api.isNecessary(body, adsType);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendTest() throws ApiException {
        BuildingsDTO body = null;
        String adsType = null;
        AdsProceedingsDTO response = api.send(body, adsType);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void xmlTest() throws ApiException {
        List<BuildingDTO> body = null;
        String adsType = null;
        AdsRequestsXmlDTO response = api.xml(body, adsType);

        // TODO: test validations
    }
}
